calificaciones_prepa <- read.csv("E:/Descargas/calificaciones_prepa.csv")
install.packages("tidyverse")
install.packages("rpart")
library(rpart)
library(tidyverse)
library(dplyr)
library(ggplot)
Mate_1<- select(calificaciones_prepa,Desc_Materia, sexo, Calif_Final) %>% filter(Desc_Materia=="MATEMATICAS_I")
ggplot(calificaciones_prepa, aes(x=sexo))+geom_bar(fill="purple")
Media <-mean(Mate_1$Calif_Final)
Desviacion <-sd(Mate_1$Calif_Final)
Mediana <-median(Mate_1$Calif_Final) 
print(paste("Promedio Calificacion Matemáticas I",Media))
print(paste("Desviación estandar Matemáticas I",Desviacion))
print(paste("Mediana de Matemáticas I",Mediana))
